### ISSUE TITLE
Multi-threaded downloads

### ISSUE THREAD

**Issue by Aptimex** [TotalJTM/PyPavlovUpdater#12]
I have some (pretty generic) code for doing multi-threaded file downloading from Mod.io here: https://github.com/Aptimex/pavlov-mod-manager/blob/main/downloads.py

Specifically, the downloadHandler() and downloadFile() functions. 

Changes required to use with your code (off the top of my head):
- Pass in a `THREADS` argument to downloadFile (I use a global)
- Modify print statements to work with whatever you do to passing stuff between frontend/backend
- Might need to fix the path slash convention, I'm using the silly Windows `\\` thing. 

Also note that my code doesn't have any way of reporting percentage updates. There might be a way to add that but I haven't looked into it.

**Comment by TotalJTM** [comment]
Changes were integrated into V1.6 GUI and V1.5 PyPavlovUpdater script
