### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by nanthony21** [TotalJTM/PyPavlovUpdater#9]
Just tried version 1.4 but any time I try to open the download menu or subscription menu the program freezes up for a long time (apparently trying to form a connection. Then I get the error shown in this log:
[pypavlovupdater.log](https://github.com/TotalJTM/PyPavlovUpdater/files/13851366/pypavlovupdater.log)

**Comment by nanthony21** [comment]
After waiting a while and trying again it started to work. Likely an issue on mod.io's side.

**Comment by TotalJTM** [comment]
Havent seen this issue in a while (outside of the window freezing up while generating new window, cant help it with PySimpleGui) so closing it for now
